### ISSUE TITLE
add test data

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2node#3]
Add a minimal set of test data that can be used for regression testing

**Comment by tomkralidis** [comment]
As discussed at today's standup, @chenxiaoxia2019 will add the equivalent SYNOP and hourly data files in https://github.com/wmo-im/wis2node/tree/main/tests/data/observations for parity, at which point we can close this issue.

**Comment by tomkralidis** [comment]
As discussed with @efucile, we do not need to provide SYNOP in test data.

**Comment by chenxiaoxia2019** [comment]
@tomkralidis I will add the hourly data for the test.
